apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-demo-deployment
  labels:
    app: mongo-demo-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-demo-2
  template:
    metadata:
      labels:
        app: mongo-demo-2
    spec:
      containers:
        - name: mondo-demo-container
          image: adamhaddad/mongo-demo-2:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: your-service
spec:
  selector:
    app: mongo-demo-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
